
    assign module_pooling = 1'b1;
    pooling_2d #(.APB_WIDTH_AD      ( P_APB_WIDTH_AD )
                ,.APB_WIDTH_DA      ( P_APB_WIDTH_DA )
                ,.M_AXI_WIDTH_ID    ( M_AXI_WIDTH_ID )
                ,.M_AXI_WIDTH_AD    ( M_AXI_WIDTH_AD )
                ,.M_AXI_WIDTH_DA    ( M_AXI_WIDTH_DA )
                ,.DATA_TYPE         ( P_DATA_TYPE    )
                ,.DATA_WIDTH        ( P_DATA_WIDTH   )
                `ifdef DATA_FIXED_POINT
                ,.DATA_WIDTH_Q      ( P_DATA_WIDTH_Q )
                `endif
              //,.KERNEL_MAX_SIZE   ( P_POOL_KERNEL_MAX_SIZE    )
              //,.FEATURE_FIFO_DEPTH( P_POOL_FEATURE_FIFO_DEPTH )
              //,.RESULT_FIFO_DEPTH ( P_POOL_RESULT_FIFO_DEPTH  )
              //,.POOLING_NOP(P_POOLING_NOP )
              //,.POOLING_MAX(P_POOLING_MAX )
              //,.POOLING_AVG(P_POOLING_AVG )
                )
    u_pooling (
          .PRESETn            ( PRESETn    )
        , .PCLK               ( PCLK       )
        , .S_APB_PSEL         ( PSEL    [2])
        , .S_APB_PENABLE      ( PENABLE    )
        , .S_APB_PADDR        ( PADDR      )
        , .S_APB_PWRITE       ( PWRITE     )
        , .S_APB_PRDATA       ( PRDATA  [2])
        , .S_APB_PWDATA       ( PWDATA     )
        , .S_APB_PREADY       ( PREADY  [2])
        , .S_APB_PSLVERR      ( PSLVERR [2])
        , .ARESETn            ( ARESETn      )
        , .ACLK               ( ACLK         )
        , .M_AXI_RST_AWID     ( m_axi_pool_AWID    )
        , .M_AXI_RST_AWADDR   ( m_axi_pool_AWADDR  )
        , .M_AXI_RST_AWLEN    ( m_axi_pool_AWLEN   )
        , .M_AXI_RST_AWSIZE   ( m_axi_pool_AWSIZE  )
        , .M_AXI_RST_AWBURST  ( m_axi_pool_AWBURST )
        , .M_AXI_RST_AWVALID  ( m_axi_pool_AWVALID )
        , .M_AXI_RST_AWREADY  ( m_axi_pool_AWREADY )
        , .M_AXI_RST_WDATA    ( m_axi_pool_WDATA   )
        , .M_AXI_RST_WSTRB    ( m_axi_pool_WSTRB   )
        , .M_AXI_RST_WLAST    ( m_axi_pool_WLAST   )
        , .M_AXI_RST_WVALID   ( m_axi_pool_WVALID  )
        , .M_AXI_RST_WREADY   ( m_axi_pool_WREADY  )
        , .M_AXI_RST_BID      ( m_axi_pool_BID     )
        , .M_AXI_RST_BRESP    ( m_axi_pool_BRESP   )
        , .M_AXI_RST_BVALID   ( m_axi_pool_BVALID  )
        , .M_AXI_RST_BREADY   ( m_axi_pool_BREADY  )
        , .M_AXI_FTU_ARID     ( m_axi_pool_ARID    )
        , .M_AXI_FTU_ARADDR   ( m_axi_pool_ARADDR  )
        , .M_AXI_FTU_ARLEN    ( m_axi_pool_ARLEN   )
        , .M_AXI_FTU_ARSIZE   ( m_axi_pool_ARSIZE  )
        , .M_AXI_FTU_ARBURST  ( m_axi_pool_ARBURST )
        , .M_AXI_FTU_ARVALID  ( m_axi_pool_ARVALID )
        , .M_AXI_FTU_ARREADY  ( m_axi_pool_ARREADY )
        , .M_AXI_FTU_RID      ( m_axi_pool_RID     )
        , .M_AXI_FTU_RDATA    ( m_axi_pool_RDATA   )
        , .M_AXI_FTU_RRESP    ( m_axi_pool_RRESP   )
        , .M_AXI_FTU_RLAST    ( m_axi_pool_RLAST   )
        , .M_AXI_FTU_RVALID   ( m_axi_pool_RVALID  )
        , .M_AXI_FTU_RREADY   ( m_axi_pool_RREADY  )
        , .interrupt          ( interrupt_pool     )
    );
